#' Read ThreeME simulation csv output generated by EViews
#'
#' @param csv.file.path file.path where to find the csv file
#' @param variables_selection optional in order to import only certain variables
#' @param scenario_label name of shock scenario to import, if NULL will use the csv filename
#'
#' @return a long format threeme dataframe
#' @export
#' @import package
#'
read_3me_eviews_csv <- function(csv.file.path = file.path("csv", "ct1.csv"),
                                variables_selection = variables_to_keep,
                                scenario_label = NULL){

  ### Checks ###
  if(is.null(scenario_label)){
    scenario_label <- stringr::str_remove(basename(csv.file.path),"\\.csv$")
  }

  data_read <- data.table::fread(input = csv.file.path,
                                 data.table = TRUE) |> stats::na.omit()
  ### ### ### ### ### ### ###


  n_scen <- names(data_read |> dplyr::select(-V1)) |> stringr::str_replace("^.+_(\\d+)$","\\1") |> unique()
  nb <- length(n_scen)

  if(length(scenario_label) < (nb-1) ){
    scenario_label <- stringr::str_c("scen", c(1:(nb-1)))
  }else{
    scenario_label<- scenario_label[1:(nb-1)]
  }

  n_scen <- purrr::set_names(n_scen,c("baseline",scenario_label ))


  ### Variable Selection ###
  if(!is.null(variables_selection)){

    data_read <- data_read |> dplyr::select (dplyr::any_of(c("V1" , purrr::map(variables_selection,~stringr::str_c(.x,n_scen,sep = "_")) |> unlist()  ) ) )

  }
  ### ### ### ### ### ### ###



  nn <- names(data_read)
  sel <- purrr::map(n_scen, function(s)keep(nn, stringr::str_detect(nn, stringr::str_c("_", s,"$") )))

  suppressWarnings({

    data_long3<- data_read |> data.table::melt(id.vars = "V1",
                                               measure= sel,
                                               variable.factor = TRUE
    )
  })
  nsel <- sel[[1]] |> stringr::str_remove('_0$')
  data_res <- data_long3[, variable_n := nsel[variable]] |>
    dplyr::select(-variable) |> dplyr::rename(variable = variable_n, year = V1) |> dplyr::relocate(variable, .after = year) |>
    dplyr::mutate(sector = NA_character_, commodity = NA_character_) |>
    as.data.frame()

}
