#' Creating the scenario calibration environment
#'
#' @description
#' The scenario calibration environment, a.k.a. the calibration bubble, creates the necessary objects from a given configuration list to test scenario calibration scripts.
#'
#' @param baseline_calibration Boolean. Whether to create an environment to test a baseline scenario calibration. Default: FALSE
#' @param configuration Configuration list to use. Defaul is config. Seldom needs user modification.
#'
#' @returns a list of all the objects necessary to test a scenario configuration script. the list needs to be expanded in the global environment
#' @export
#' @importFrom data.table fread
#' @import dplyr
#'
#' @examples
#' \dontrun{
#'   config <- readconfig(
#'   input_config_file = file.path("configuration", "config_input_threeme.R"),
#'   output_config_file = file.path("configuration", "config_output_threeme.R"))
#'
#'   calibration_environment(FALSE, config) |> list2env(envir = globalenv())
#'
#' }
#'
#'
calibration_environment <- function(baseline_calibration = FALSE,
                                    configuration = config){

  # config <- NULL
  input <- NULL
  baseyear <- NULL
  lastyear <- NULL
  shockyear <- NULL
  max_lags <- NULL
  firstyear <- NULL
  classification <- NULL
  calib_baseline <- NULL
  baseline_ch <- NULL


  run_dynamo(config_list = configuration)

  list2env(configuration,envir = environment())
  list2env(input,envir = environment())

  # Calibration of baseline and scenario shocks script : objective is to create the calibration databases for the baseline and for each shock.

  ## A. Loading calib.csv generated by dynamo

  calib <- data.table::fread("src/compiler/calib.csv", data.table = FALSE) |>
    dplyr::select(-dplyr::all_of("baseyear")) |>
    dplyr::mutate(year = year + input$baseyear)

  OGcalib <- calib
  return_list <- list(
                      OGcalib = OGcalib,
                      baseyear = baseyear,
                      lastyear = lastyear,
                      shockyear = shockyear,
                      max_lags = max_lags,
                      firstyear = firstyear,
                      classification = classification)
  ## B Baseline shock calibration (ie deviating from the steady state at the baseline configuration)
  if(baseline_calibration == FALSE){
    source(calib_baseline,local = TRUE)
    write.csv(baseline_ch,
              file = file.path("configuration","scenarii_calib","calib_baseline.csv"),
              row.names = FALSE)

    ## C Modified calib to integrate potential baseline changes

    baseline_vars <- setdiff(names(baseline_ch), "year")

    calib_new_base <- OGcalib |>
      dplyr::filter(year %in% c(firstyear:lastyear)) |>
      dplyr::select(-dplyr::all_of(baseline_vars)) |>
      dplyr::full_join(baseline_ch, by= "year")
    ### calib_new_base now integrates changes with the baseline scenario and should be used to configure shock scenarii
    return_list <- list(calib_new_base = calib_new_base,
                        OGcalib = OGcalib,
                        baseyear = baseyear,
                        lastyear = lastyear,
                        shockyear = shockyear,
                        max_lags = max_lags,
                        firstyear = firstyear,
                        classification = classification)
  }
   return_list

}

# plop <- calibration_environment()
